apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS5kZW1vL3JlcG9zaXRvcnkvc2VydmljZS1zdGFydGVyLWRvY2tlciI6IHsKICAgICAgImF1dGgiOiAiWVdSdGFXNDZWR2h2ZFdkb2RFQmpZWFJoYkhsemRBPT0iCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson